apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault-config.hcl: |
    storage "postgresql" {
      connection_url = "postgresql://vault:password@postgres:5432/vault"
    }
    
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }
